# Generated by Django 3.0.2 on 2020-12-11 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailsent',
            old_name='mail_receipent',
            new_name='mail_recipient',
        ),
    ]
