# Generated by Django 3.0.2 on 2020-12-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201211_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsent',
            name='contact_name',
            field=models.CharField(default='', max_length=180),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emailsent',
            name='mail_recipient',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='emailsent',
            name='mail_sender',
            field=models.CharField(max_length=255),
        ),
    ]
